name: Bug Report
description: Report a UserScript or feature that is not working as expected.
labels: [bug]
body:
  - type: input
    id: userscript
    attributes:
      label: Which UserScript is not working?
      placeholder: DisableFocusCheck
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug?
      description: A clear and consice description of the issue
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: What Browser are you using?
      description: (Including version number)
      placeholder: Firefox 137.0.2
    validations:
      required: true
  - type: input
    id: userscript-loader
    attributes:
      label: Which UserScript Loader are you using?
      description: (Including version number)
      placeholder: Tampermonkey 5.3.3
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false